### ISSUE TITLE
Raise for status option in GraphQL query

### ISSUE THREAD

**Issue by davidban77** [nautobot/pynautobot#12]
## Versions

Nautobot: 1.0.0b4
pynautobot: 1.0.2

## Problem statement

First time using this SDK and liking it! :)

I do not know how this error is handled on the REST endpoint for this SDK, but when executing a GQL on a non-existing device, the errors are not handled:

```python
In [22]: gql_respone = nautobot.graphql.query(query=GET_DEVICE_DATA_QUERY, variables={"device_id": 'DUMMY'})

In [23]: gql_respone.status_code
Out[23]: 200

In [24]: gql_respone.json
Out[24]: {
    'errors': [{'message': "['“DUMMY” is not a valid UUID.']", 'locations': [{'line': 2, 'column': 3}], 'path': ['device']}],
    'data': {'device': None}
}

# OR

In [25]: gql_respone = nautobot.graphql.query(query=GET_DEVICE_DATA_QUERY, variables={"device_id": 'f2533477-5e9f-4741-b787-70ba36f7e447'})

In [26]: gql_respone.status_code
Out[26]: 200

In [27]: gql_respone.json
Out[27]: {
    'errors': [{'message': 'Device matching query does not exist.', 'locations': [{'line': 2, 'column': 3}], 'path': ['device']}],
    'data': {'device': None}
}
```

In this example I am trying to collect the device data on the `device` endpoint using its `UUID`.

The result is returning a 200 status, which I do not know if is really ok since the data is missing, and the only way to check for an error is to validate the returned output.

## Proposal

It would be nice to have a method similar to requests `raise_for_status()` for well known error like `Not valid UUID` or `Device matching. query does not exist`, along with their correct status codes (400 or 404)

**Comment by davidban77** [comment]
I see that there is already a `GraphQLException`, nice!

So maybe improving the response data analysis might help here:

https://github.com/nautobot/pynautobot/blob/develop/pynautobot/core/graphql.py#L128-L136

**Comment by dgarros** [comment]
From a GraphQL standpoint this is a bit tricky because it's possible to have multiple GraphQL queries in a single request. This is why the API is returning 200 even if there is an error in one of the request today.
Having said that I see the value to get a 4xx code when one of the request generates an error, I would recommend to start a discussion in core to see if we should change the code returned by the API directly

**Comment by jmcgill298** [comment]
I think it is a fair question for what pynautobot should do. We discussed this during the creation of that code, and I lean slightly towards raising an exception, but that did increase complexity and time to complete (particularly for the case that @dgarros mentioned above).

**Comment by jvanderaa** [comment]
I think the core discussion route is the appropriate route here as well. Going to close this issue. @davidban77
