### ISSUE TITLE
custom field endpoint

### ISSUE THREAD

**Issue by gygetho** [nautobot/pynautobot#141]
Since the method custom_fields() was introduced in app.py, you're not able to get the custom_fields endpoint anymore because api.extras.custom_fields pointing to the method custom_fields() of app.py. in Version 1.5 the following code was working:

nautobot = api(url=na_url, token=token)
cf_model = nautobot.extras.custom_fields
cf_model.create(data)

on newer versions, the workaround looks like this:
nautobot = api(url=na_url, token=token)
cf_model = nautobot.extras.__getattr__("custom_fields")
cf_model.create(data)

the same applies to "custom_field_choises"

**Comment by pszulczewski** [comment]
@gygetho many thanks for reporting that issue. We missed that overlap in the PR from the community to tidy up naming. Fix on its way.

**Comment by gygetho** [comment]
@pszulczewski Patryk, thanks a lot! You guys doing a great job! I appreciate your work!
