### ISSUE TITLE
Add notes support for all models that support notes

### ISSUE THREAD

**Issue by whitej6** [nautobot/pynautobot#159]
# Improve notes support

## Current State

API does not have a "notes" attr in the return payload and only returns "notes_url" as a link to a list view for all notes that apply to the current instance.

## Proposal

Provide ".notes" on any model that provides notes and the attribute would be an `pynautobot.core.endpoint.Endpoint` to allow for create update and delete operations scoped to just the current model instance

## Example desired outcome

```python
dev = py_nb.dcim.devices.get(name="foo")
count(dev.notes.all()) # return N notes created on a device named foo
note = dev.notes.create(note="bar")
note.note="baz"
note.save()

count(dev.notes.all()) # return being N+1 of previous count
```

**Comment by jvanderaa** [comment]
Working on checking some things out on this. But first look at using demo.nautobot.com as a reference, there is a notes API endpoint: `/extras/notes`.

There is an `assigned_object_id` reference on the GET reference that would be used to get the notes for the object.

**Comment by jvanderaa** [comment]
So what we are looking at really is a convenience function to help things out, rather than anything is not usable today right?

**Comment by whitej6** [comment]
It's a convenience method to match API functionality. When using `/api/dcim/devices/<uuid>/notes/` you can post with just `{"note": "some note"}` without having to account for generic foreign key etc. Also the same endpoint will return a list of all notes for just the one device.
