### ISSUE TITLE
Feature: Add User Agent Information

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/pynautobot#199]
It would be good to enhance things further to provide the option to have a header that gives the user/agent.

**Comment by joewesch** [comment]
There was already a PR to add this and a conclusion that it is already possible: https://github.com/nautobot/pynautobot/pull/171#issuecomment-2104209674

**Comment by nrnvgh** [comment]
My two cents: We actually ran into a case recently where having the client send a vendor-side user-agent would have been useful; specifically, being able to run reports to determine what version of pynautobot our customers were using; having that in the user-agent header would have been useful.

**Comment by joewesch** [comment]
Closed via #207
