### ISSUE TITLE
No response when creating records

### ISSUE THREAD

**Issue by willervinNTS** [nautobot/pynautobot#22]
I'm attempting to take a list of devices from a csv file and import them to my nautobot instance. It's my understanding that I need to create records before I do so. I created this method, for example, to create device roles. (I'm also attempting to create device_types and sites records)
![image](https://user-images.githubusercontent.com/53794492/135329807-4c3f3f9b-9c86-44bc-96e0-65be53dc3a92.png)
I'm receiving no response from the api and I'm wondering if there is something missing from my config object that is required to create a record? 

Also, if this is the wrong approach to importing devices, please let me know. Thanks!

**Comment by jmcgill298** [comment]
`I'm receiving no response from the api` where in the code are you expecting something? What is it you are expecting?

**Comment by willervinNTS** [comment]
When I print access_role.name I get an error: `AttributeError: object has no attribute "name"` so I know that the record was not actually created but I receive no error/response from the server as to why `device_roles.create(**config)` has failed

**Comment by jmcgill298** [comment]
what type of object is `access_role`? what attributes are on the object?

**Comment by willervinNTS** [comment]
Object is of type `<class 'pynautobot.core.response.Record'>`. These are it's attributes 
![image](https://user-images.githubusercontent.com/53794492/135333803-a3f5d1a6-f1ce-44b5-9b95-802ce96b4e29.png)

**Comment by jmcgill298** [comment]
I am not able to replicate this using v1.0.3; can you provide the role name to see if there is something with the name (not likely)

**Comment by willervinNTS** [comment]
The role name is `LAN Router` and I'm on v1.1.2

**Comment by jmcgill298** [comment]
v1.1.2 of nautobot? I was referring to pynautobot. I testing pynautobot 1.0.3 and nautobot v1.1.2 and I do get the expected exception when trying to use that (that will not be a valid slug name). Do you have a try/except block that is eating that exception?

**Comment by willervinNTS** [comment]
Sorry, yes I'm using nautobot v1.1.2 and pynautobot 1.0.3. I don't have a try/except block as it's not actually throwing an error. I changed the slug name so that it's valid: `"slug": role.lower().replace(' ', '-')` which looks like `lan-router` and I'm still getting the same result

**Comment by jmcgill298** [comment]
is the device_role created in Nautobot?

**Comment by willervinNTS** [comment]
Would you mind clarifying what you mean by that?

**Comment by jmcgill298** [comment]
if you check in the GUI or the database table, was that entry created?

**Comment by willervinNTS** [comment]
Negative. I've even tried hard coding the data to see if it works, but no success:
![image](https://user-images.githubusercontent.com/53794492/135351733-16f46dad-b62d-43ba-aa0e-4d19b8a0326e.png)

It does however work if use the web api to import the data:
![image](https://user-images.githubusercontent.com/53794492/135351519-ac0726af-7b70-432a-9244-c7fc099d7a19.png)

**Comment by willervinNTS** [comment]
Is there a way to get a response code/body from the server so that I might see why my data is invalid?

**Comment by jmcgill298** [comment]
your best bet is to insert a break point and walk through the debugger.

I have tried passing good data, bad data, invalid token, and invalid permissions, and all cases result in the expected behavior: the new object, Request Errors with the expected HTTP response for the error.

**Comment by willervinNTS** [comment]
I couldn't seem to pinpoint the problem using breakpoints. I instead went with the requests library which now seems to be working fine

**Comment by jmcgill298** [comment]
Thanks for following up, I will leave this open for a short time in case anyone else can reproduce this.
