### ISSUE TITLE
pynautobot reqquest error

### ISSUE THREAD

**Issue by nanisyako** [nautobot/pynautobot#23]
I am trying to flter devices based on their tags it is working on and off but I am not what is the reason
the environment
nornir 3.1.1 and Nautobot 1.0.3

```
File "/home/test/pynet_nautobot/lib64/python3.6/site-packages/pynautobot/core/query.py", line 226, in _make_call
    raise RequestError(req)
pynautobot.core.query.RequestError: The request failed with code 504 Gateway Time-out but more specific details were not returned in json. Check the Nautobot Logs or investigate this exception's error attribute.
```

and here is the init file
```
    nr = InitNornir(
        inventory={
            "plugin": "NautobotInventory",
            "options": {
                "nautobot_url": nb_url,
                "nautobot_token": nb_token,
                "ssl_verify": False,
            },
        },
    )

nb = pynautobot.api(url=nb_url,token=nb_token)
    nb.http_session.verify = False
    
    fd = {}
    smartnet_devices=[]
    for a in filt:
        k, v = a.split(':')
        fd[k] = v
    #ff = F(**fd)
    
    #print(type(ff))
        new_devices = nb.dcim.devices.filter(tag=[f"{v}"])
        smartnet_devices.extend(new_devices)
        #import ipdb ; ipdb.set_trace()
    my_device_list = list(set(smartnet_devices))    
    nr = nr.filter(F(name__any= [f"{items}" for items in my_device_list]))
```
If I try to run the script couple of items then it works

**Comment by jmcgill298** [comment]
It looks like Nautobot is returning a 504

**Comment by nanisyako** [comment]
is there a way of increasing that timeout value? since it is working intermittently? or is there a way of getting more details like why nautobot can't return the requested data on time?

**Comment by jmcgill298** [comment]
It would be best to open an issue on the [Nautobot Repo](https://github.com/nautobot/nautobot/issues). There would be several things to look at, two that come to mind is that it the query is taking too long, and caching is allowing subsequent calls to work, or that there are several requests being sent to the web service, and it is taking too long to process the request.

**Comment by FragmentedPacket** [comment]
Appears it was resolved by excluding config contexts. Closing for now.
