### ISSUE TITLE
Support add_params in EndPoint

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/pynautobot#24]
There are a few params that would be nice to be able to pass through on the endpoints, for `filter()` and `all()` if possible. We should add the ability to exclude config contexts and to include computed fields. 

On the config contexts part, it is known that this is an expensive query to make. The nornir-nautobot inventory with REST API is using pynautobot to make this call. This is causing some timeouts at times on larger instances. Would like to have this capability to remove the call to get config contexts.

On the computed fields front, a new parameter was added. This would be good to add into the capabilities as long as params are being edited and looked at in the same light as excluding config contexts.

**Comment by jmcgill298** [comment]
ya, I wouldn't expect it to work on `all()`, but was pretty sure that it would for `filter()`; can this be closed?
