### ISSUE TITLE
AttributeError being raised for prefix object when trying to retrieve tags

### ISSUE THREAD

**Issue by thatfatguypat** [nautobot/pynautobot#53]
In my org we add tags to network prefixes as an identifier, and use those tags as a filter to find prefixes.  We then perform different operations based on the combination of tags assigned to the prefixes.  I can still use the filter on a get(), which provides me a list of prefixes with the tag, but I can no longer retrieve all tags assigned to the resulting prefixes by accessing the `tags` attribute of the prefixes.  

The code below would previously return a list of tags for `prefix_obj.tags` in v1.0.4.  However, in v1.1.1 the same code raises an AttributeError for the 'prefix' attribute being missing.

```
>>> import pynautobot
>>> url="https://my.nautobot.net"
>>> token='1234mocktoken5678'
>>> nautobot=pynautobot.api(url=url,token=token)
>>> name='prefix-tag-1'
>>> prefix = '10.0.0.0/26'
>>> network = prefix.split("/")[0]
>>> mask = int(prefix.split("/")[1])
>>> vrf = 'my-vrf-uuid-here'
>>> prefix_obj = nautobot.ipam.prefixes.get(q=network, mask_length=mask, vrf_id=vrf)
>>> type(prefix_obj)
<class 'pynautobot.models.ipam.Prefixes'>
>>> prefix_obj.tags

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pynautobot/core/response.py", line 216, in __repr__
    return str(self)
  File "/usr/local/lib/python3.7/site-packages/pynautobot/models/ipam.py", line 29, in __str__
    return str(self.prefix)
  File "/usr/local/lib/python3.7/site-packages/pynautobot/core/response.py", line 197, in __getattr__
    raise AttributeError('object has no attribute "{}"'.format(k))
AttributeError: object has no attribute "prefix"
```
I noticed this change in [response.py](https://github.com/nautobot/pynautobot/blob/develop/pynautobot/core/response.py#L174-L176) from #41 which redefined `self.default_ret = self.endoint.return_obj`.  Reverting this appears to resolve my issue, but I don't have enough context as to the intent of the original change so I am not sure if that is the correct course of action.

serialize() on the prefix object, with some data redacted, shows that 'prefix' attribute exists, contrary
to what is indicated by the AttributeError:
```
>>> prefix_obj.serialize()
{'id': '<object-uuid-here>', 
'url': 'https://my.nautobot.net/api/ipam/prefixes/<uuid>/', 
'family': 4, 'prefix': '10.0.0.0/26', 'site': None, 'vrf': '<redacted>',
'tenant': '<redacted>', 'vlan': None, 'status': 'active', 'role': '<redacted>', 'is_pool': False, 
'description': 'my-prefix-description', 'tags': ['prefix-tag-1'], 'custom_fields': {'my_custom_field': None},
'created': '2022-01-18', 'last_updated': '2022-01-18T23:24:28.624153Z', 'display': '10.0.0.0/26'
}
```

**Comment by thatfatguypat** [comment]
I think this might be related to [ipam.py](https://github.com/nautobot/pynautobot/blob/develop/pynautobot/models/ipam.py#L22-L24) trying to return `self.prefix` here but I don't know what is calling __str__ or what attribute could be returned from `__str__` instead when  `hasattr(self, "prefix")` is false.

**Comment by thatfatguypat** [comment]
I modified this section of ipam.py](https://github.com/nautobot/pynautobot/blob/develop/pynautobot/models/ipam.py#L27-L29) to print out `vars(self)` and `type(self)` so I could better understand the exception being raised.  Calling `prefix_obj.tags` as mentioned in the initial description appears to create a 'pynautobot.models.ipam.Prefixes' type object, which will try to return `self.prefix` in the `__str__` method but since the tags don't have a prefix attribute, this results in the AttributeError.

**Comment by glennmatthews** [comment]
@jmcgill298 I don't think #55 looks right either, based on my admittedly limited understanding. I'd expect that *in most cases*, `<Record subclass>.<arbitrary attribute>` should *not* automatically be an instance of the same parent subclass. I think #41 made too sweeping of a change.

**Comment by jmcgill298** [comment]
@glennmatthews I think my comment on the referenced PR communicates that I'm not in disagreement with you. One point to clarify is that most attributes are not made into an instance of a Record class. As to whether most attributes that are converted into a Record class should use the base class or a subclass, like you, I don't have enough context to know the answer. The approach I took in my PR was to only change what we know is not working, and leave everything else as is (instead of breaking things in new ways).
