### ISSUE TITLE
List prefixes broken in 1.1.2

### ISSUE THREAD

**Issue by nniehoff** [nautobot/pynautobot#74]
After some testing `prefix.available_prefixes.list()` returns a list of null values in version 1.1.2.  Here is some test code:

```python
import pynautobot

nautobot_url = "https://demo.nautobot.com"
api_token = ""
prefix_id = "08dabdef-26f1-4389-a9d7-4126da74f4ec"

nautobot = pynautobot.api(
    url=nautobot_url,
    token=api_token,
)

prefix = nautobot.ipam.prefixes.get(prefix_id)
print(prefix.available_prefixes.list())
```

In my testing I found:

* Python 3.10 Nautobot 1.4.1 pynautobot 1.0.2 through 1.1.1 returns
[10.35.0.0/16, 10.36.0.0/14, 10.40.0.0/13, 10.48.0.0/12, 10.64.0.0/10, 10.128.0.0/9]

* Python 3.10 Nautobot 1.4.1 pynautobot 1.1.2 returns
[, , , , , ]

**Comment by FragmentedPacket** [comment]
Closed via #75
