### ISSUE TITLE
Feature: Removing the restriction on `id` for filter

### ISSUE THREAD

**Issue by jifox** [nautobot/pynautobot#76]
In nornir-nautobot I tried to restrict the inventory to a single host by filtering by "device id".

This is not possible beacuse pynautobot has a restriction to use `id` as a filter.

> @jvanderaa on slack
> And that is definitely on pynautobot setting here. I'll have to see about removing the restriction there.
> So the work around at this point would to filter after the inventory.

Please remove the  the restriction on `id` for filter (devices, ...)

**Comment by hemantwasthere** [comment]
Hey @jifox ,  I would like to work on this issue

**Comment by jifox** [comment]
@hemantwasthere Yes, I will try to implement that

**Comment by hemantwasthere** [comment]
Okay @jifox
